"use client"


import type { Metadata } from "next";
import { Geist, Geist_Mono, Exo } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";
import { Toaster } from "@/components/ui/sonner"
import MyProvider from "./_components/MyProvider/MyProvider";
import CartContextProvider from "../context/CartContext"


const exoFallback = Exo({
  subsets : ["latin"],
  variable:"--font-exo",
  weight:["400","600","700"]

})
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      
    >
      <head>
        <title>FreshCart</title>
      </head>
      <body className={`${exoFallback.className}`} >
        <MyProvider>
      <CartContextProvider>

        <Navbar />
        <Toaster/>
        {children}

        <Footer />
      </CartContextProvider>
        </MyProvider>
      </body>
    </html>
  );
}
