


import type { Metadata } from "next";
import { Geist, Geist_Mono, Exo } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";
import { Toaster } from "@/components/ui/sonner"
import MyProvider from "./_components/MyProvider/MyProvider";


const exoFallback = Exo({
  subsets : ["latin"],
  variable:"--font-exo",
  weight:["400","600","700"]

})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      
    >
      <body className={`${exoFallback.className}`} >
        <MyProvider>

        <Navbar />
        <Toaster/>
        {children}

        <Footer />
        </MyProvider>
      </body>
    </html>
  );
}
